// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtY8SluJCh8DgPQOc_Vh6q9xynE3kNP40',
    appId: '1:341419249481:web:296a6f4ec5a9644c445498',
    messagingSenderId: '341419249481',
    projectId: 'give-and-take-4d7d2',
    authDomain: 'give-and-take-4d7d2.firebaseapp.com',
    storageBucket: 'give-and-take-4d7d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfDGM1HMzeS57zbgiOZ_CBjtE-thidx5U',
    appId: '1:341419249481:android:f5b3702b6a77eb2c445498',
    messagingSenderId: '341419249481',
    projectId: 'give-and-take-4d7d2',
    storageBucket: 'give-and-take-4d7d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCquzjIaAO2c-yBVZEo487rhPzwXj0lyvg',
    appId: '1:341419249481:ios:9beaeda136cf20e0445498',
    messagingSenderId: '341419249481',
    projectId: 'give-and-take-4d7d2',
    storageBucket: 'give-and-take-4d7d2.firebasestorage.app',
    iosBundleId: 'com.example.giveAndTake',
  );
}
